In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset=pd.read_csv("C:\\Users\\DADA\\Documents\\purchased.csv")
dataset



States   age   salary purchase
0       texas  44.0  72000.0       No
1     florida  27.0  48000.0      Yes
2  california  30.0  54000.0       No
3       texas  38.0  61000.0       No
4  california   NaN  65000.0      Yes
5       texas  35.0  58000.0      Yes
6     florida  50.0  83000.0       No
7       texas  37.0  67000.0      Yes

In [3]:
pd.isnull(dataset).sum()

States      0
age         1
salary      0
purchase    0
dtype: int64

In [4]:
dataset.describe()

age        salary
count   7.000000      8.000000
mean   37.285714  63500.000000
std     7.867958  10915.257997
min    27.000000  48000.000000
25%    32.500000  57000.000000
50%    37.000000  63000.000000
75%    41.000000  68250.000000
max    50.000000  83000.000000

In [5]:
#seperating independent and dependent values in array form
x=dataset.iloc[:,0:3].values

In [9]:
x
np.shape(x)

(8, 3)

In [10]:
y=dataset.iloc[:,3].values
y
np.shape(y)

(8,)

In [11]:
#handling the missing data
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
x[:,1:]=imputer.fit_transform(x[:,1:])
x

array([['texas', 44.0, 72000.0],
       ['florida', 27.0, 48000.0],
       ['california', 30.0, 54000.0],
       ['texas', 38.0, 61000.0],
       ['california', 37.285714285714285, 65000.0],
       ['texas', 35.0, 58000.0],
       ['florida', 50.0, 83000.0],
       ['texas', 37.0, 67000.0]], dtype=object)

In [12]:
#changing state name(categorical) from string to integers because in ml all should be in numbers only
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[("encode",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)
x



array([[0.0, 0.0, 1.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 37.285714285714285, 65000.0],
       [0.0, 0.0, 1.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 37.0, 67000.0]], dtype=object)

In [14]:
#avoiding the dummy variable trap
x=x[:,1:]
np.shape(x)




(8, 3)

In [15]:
#splitting into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train
np.shape(x_train)


(6, 3)

In [16]:
np.shape(y_train)

(6,)

In [19]:
np.shape(x_test)

(2, 3)

In [20]:
np.shape(y_test)

(2,)

In [21]:
x_test

array([[0.0, 50.0, 83000.0],
       [0.0, 30.0, 54000.0]], dtype=object)

In [22]:
y_train

array(['Yes', 'Yes', 'No', 'No', 'Yes', 'Yes'], dtype=object)

In [23]:
y_test

array(['No', 'No'], dtype=object)

In [24]:
#changing all values to standard form
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [25]:
x_train

array([[-1.41421356, -1.86514231, -1.81945807],
       [ 0.70710678,  0.12308046,  0.67955663],
       [ 0.70710678,  0.32190273, -0.10960591],
       [ 0.70710678,  1.51483639,  1.33719208],
       [ 0.70710678, -0.2745641 , -0.50418718],
       [-1.41421356,  0.17988682,  0.41650245]])

In [26]:
x_test

array([[-1.41421356,  2.70777005,  2.78399006],
       [-1.41421356, -1.26867548, -1.03029554]])